<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FbBasic\View\Helper\Coverphotohelper'       => __DIR__ . '/src/FbBasic/View/Helper/Coverphotohelper.php',
    'FbBasic\View\Helper\Graphhelper'            => __DIR__ . '/src/FbBasic/View/Helper/Graphhelper.php',
    'FbBasic\View\Helper\Locationhelper'         => __DIR__ . '/src/FbBasic/View/Helper/Locationhelper.php',
    'FbPage\Controller\AbstractController'       => __DIR__ . '/src/FbPage/Controller/AbstractController.php',
    'FbPage\Controller\AlbumController'          => __DIR__ . '/src/FbPage/Controller/AlbumController.php',
    'FbPage\Controller\EventController'          => __DIR__ . '/src/FbPage/Controller/EventController.php',
    'FbPage\Controller\IndexController'          => __DIR__ . '/src/FbPage/Controller/IndexController.php',
    'FbPage\Controller\PostController'           => __DIR__ . '/src/FbPage/Controller/PostController.php',
    'FbPage\Factory\Options\FacebookOptions'     => __DIR__ . '/src/FbPage/Factory/Options/FacebookOptions.php',
    'FbPage\Factory\Options\FacebookPageOptions' => __DIR__ . '/src/FbPage/Factory/Options/FacebookPageOptions.php',
    'FbPage\Factory\Service\FacebookFactory'     => __DIR__ . '/src/FbPage/Factory/Service/FacebookFactory.php',
    'FbPage\Factory\Service\FacebookPageFactory' => __DIR__ . '/src/FbPage/Factory/Service/FacebookPageFactory.php',
    'FbPage\Options\FacebookOptions'             => __DIR__ . '/src/FbPage/Options/FacebookOptions.php',
    'FbPage\Options\FacebookPageOptions'         => __DIR__ . '/src/FbPage/Options/FacebookPageOptions.php',
    'FbPage\Service\FacebookAbstract'            => __DIR__ . '/src/FbPage/Service/FacebookAbstract.php',
    'FbPage\Service\FacebookPage'                => __DIR__ . '/src/FbPage/Service/FacebookPage.php',
);
