<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FbPage\Factory\Service\FacebookFactory' => __DIR__ . '/src/FbPage/Factory/Service/FacebookFactory.php',
    'FbPage\Options\ModuleOptions'           => __DIR__ . '/src/FbPage/Options/ModuleOptions.php',
);
