

<?php

/**
* @var $pageWidget \FbPage\View\Helper\PageWidget
*/
$pageWidget = $this->pageWidget();
/**
* @var $graphWidget \FbBasic\View\Helper\GraphWidget
*/
$graphWidget = $this->graphWidget();
?>


<ul>
    <li><a href="<? echo $this->url("fbpage_posts");?>"><?echo $this->translate("posts");?> <span class="badge"><? echo $pageWidget->fetchAllPosts()->count();?></span></a></li>
    <li><a href="<? echo $this->url("fbpage_events");?>"><?echo $this->translate("events");?> <span class="badge"><? echo $pageWidget->fetchAllEvents()->count();?></span></a></li>
    <li><a href="<? echo $this->url("fbpage_albums");?>"><?echo $this->translate("albums");?> <span class="badge"><? echo $pageWidget->fetchAllAlbums()->count();?></span></a></li>
</ul>

<div class="panel panel-default">
    <div class="panel-heading">Page Infos</div>
    <div class="panel-body">
        <?
        echo $pageWidget->fetchPageInfo();
        ?>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Graph Widget Fetch a Page</div>
    <div class="panel-body">
        <?
        echo $graphWidget->fetchPage("140631369330249");
        ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Graph Widget Fetch a Event</div>
    <div class="panel-body">
        <?
        echo $graphWidget->fetchEvent("1042485019138787");
        ?>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Events by Page</div>
    <div class="panel-body">
        <?
        echo $pageWidget->fetchAllEvents();
        ?>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Milestones by Page</div>
    <div class="panel-body">
        <?
        echo $pageWidget->fetchAllMilestones();
        ?>
    </div>
</div>