<h2><? echo $headline;?></h2>

<table class="table-bordered">
    <thead>
    <tr>
        <td>Feld</td>
        <td>Wert</td>
    </tr>

    </thead>
    <tbody>
    <?
    /* @var $item Facebook\GraphNodes\GraphNode */
    $fieldnames = $item->getFieldNames();
    foreach ($fieldnames AS $fieldName) {
        ?>
        <tr>
            <td><? echo $fieldName; ?></td>
            <td>
                <? echo $this->graphhelper($item->getField($fieldName)); ?>&nbsp;
            </td>
        </tr>
        <?
    }

    ?>
    </tbody>
</table>

<div class="row">
    <?
    if(count($items)){
        foreach ($items AS $item) {
            /* @var $item Facebook\GraphNodes\GraphNode */
            //var_dump($item);
            ?>
            <div class="col-xs-4 col-md-2">
                <a href="#" class="thumbnail">
                    <? echo $this->graphhelper($item); ?>
                </a>
            </div>
            <?
        }
    }
    ?>
</div>



