<?php
/**
 * Created by IntelliJ IDEA.
 * User: Besitzer
 * Date: 13.09.2016
 * Time: 14:53
 */
?>
<table class="table-bordered table table-responsive">
    <thead class="thead-default">
    <tr>
        <td><? echo $this->translate("Key");?> </td>
        <td><? echo $this->translate("Type");?> </td>
        <td><? echo $this->translate("Value");?> </td>
    </tr>

    </thead>
    <tbody>
    <?
    foreach($list AS $key => $value){
        if(is_object($value)){
            $value = $this->graphdump(null,$value);
        }
        if(is_array($value)){
            $value = $this->partial('widget/default/partial/dump.phtml', array("list"=>$value));
        }
        ?>
        <tr>
            <td><? echo $key;?></td>
            <td><? echo gettype($value);?></td>
            <td><? echo $value;?></td>
        </tr>
        <?
    }
    ?>
    </tbody>
</table>