<h2><? echo $headline;?></h2>

<table class="table-bordered">
    <thead>
    <tr>
        <td>Feld</td>
        <td>Wert</td>
    </tr>

    </thead>
    <tbody>
    <?
    /* @var $item Facebook\GraphNodes\GraphNode */
    $fieldnames = $item->getFieldNames();
    foreach ($fieldnames AS $fieldName) {
        ?>
        <tr>
            <td><? echo $fieldName; ?></td>
            <td>
                <? echo $this->graphfield($fieldName,$item->getField($fieldName)); ?>&nbsp;
            </td>
        </tr>
        <?
    }

    ?>
    </tbody>
</table>


